type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  lastLogin: Timestamp
}

type Dataset @table {
  name: String!
  uploadDate: Timestamp!
  fileType: String!
  storagePath: String!
  description: String
  originalFilename: String
  user: User
}

type AnalysisConfiguration @table {
  name: String!
  analysisType: String!
  createdAt: Timestamp!
  parameters: String
  description: String
  user: User
  dataset: Dataset
}

type AnalysisResult @table {
  runDate: Timestamp!
  status: String!
  resultData: String!
  notes: String
  visualizationType: String
  user: User
  dataset: Dataset
  analysisConfiguration: AnalysisConfiguration
}

type Share @table {
  sharedAt: Timestamp!
  shareType: String!
  sharedEntityId: UUID!
  permissions: String
  sharer: User
  sharee: User
}